# Use specific windows on specific workspaces
windowrule {
  name = discord-open
  match:class = (discord)
  workspace = 2
  no_initial_focus = true
}

windowrule {
  name = steam-open
  match:class = (steam)
  no_initial_focus = true
}

windowrule {
  name = fix-steam-float
  match:class = steam
  match:initial_title = Steam
  match:float = 1

  float = off
  maximize = on
}


windowrule {
  name = chromium-open
  match:class = (chromium)
  workspace = 4
  no_initial_focus = true
}

windowrule {
  name = fullscreen-steam-games
  match:class = ^steam_app_\d+$
  fullscreen = on
}

# proton pass
windowrule {
  name = proton-pass-open
  match:class = (Proton Pass)
  float = on
  size = 1980 1080
}

